language: objective-c
osx_image: xcode11

# Set up our rubygems (slather and xcpretty, namely)
install: 
 - gem install xcpretty slather -N
 
before_script:
# Start by removing any lingering codecov files. These can cause issues when the xcode version changes
  - find . -name "*.gcda" -print0 | xargs -0 rm

# Tell the shell to echo failure codes up the pipe so that Travis will properly fail the
# build when the xcodebuild command fails
  - set -o pipefail

script:  
# Run the build script
  - ./build.py

after_success:
    - ./build_docs.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: docs.temp/docs
  on:
    branch: master

notifications:
  slack:
    secure: BIziStN+8QJLjdqNbLyRWWw9kI/MQsX+rZq+xz/bfTANk0gbEryLgMSiEoHxdoctu0dOqOet1voYuDKs3RQW3W0yh0AhDwVgWThNkTA0oDXF8zqm9AXettXNtmYHipaYb6+z6L4lpJOkClQp3hAheu8cM2igqye1O0FQla9g/PA=


